### ISSUE TITLE
Mixin issue

### ISSUE THREAD

**Issue by iPollox** [kregerl/Automatic-Elytra#1]
It's easier for me to report it through here as curseforge doesn't allow me to do comments on my browser, anyways the latest version throws this error:

`[main/FATAL]: Mixin prepare failed preparing FireworkItemMixin in automaticelytra.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'com.loucaskreger.automaticelytra.mixin.FireworkItemMixin' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'com.loucaskreger.automaticelytra.mixin.FireworkItemMixin' was not found`

Using:
- fabricloader 0.11.6
- fabric-api-0.36.0+1.17

**Comment by baltassarmonkey** [comment]
Had the same, [full log](https://pastebin.com/AdUzxN51) if this helps.

**Comment by iPollox** [comment]
I removed the mixin from the json and seems to work

**Comment by kregerl** [comment]
This has been fixed, had an old mixin in the json.
